#==============================================================================
# nfx::graphics - Sources
#==============================================================================

set(NFX_GRAPHICS_SOURCES
    src/gl/material/ibl/BrdfLutGenerator.cpp
    src/gl/material/ibl/IrradianceMapGenerator.cpp
    src/gl/material/ibl/PrefilteredEnvGenerator.cpp
    src/gl/material/BlinnPhong.cpp
    src/gl/material/Pbr.cpp
    src/gl/material/Unlit.cpp
    src/gl/material/Material.cpp
    src/gl/mesh/Mesh.cpp
    src/gl/mesh/Primitive.cpp
    src/gl/pipeline/passes/AxesPass.cpp
    src/gl/pipeline/passes/DirectionalShadowPass.cpp
    src/gl/pipeline/passes/EnvironmentPass.cpp
    src/gl/pipeline/passes/GeometryPass.cpp
    src/gl/pipeline/passes/GridPass.cpp
    src/gl/pipeline/passes/ImagePlanePass.cpp
    src/gl/pipeline/passes/OutlinePass.cpp
    src/gl/pipeline/passes/PointShadowPass.cpp
    src/gl/pipeline/passes/PostProcessPass.cpp
    src/gl/pipeline/passes/PresentPass.cpp
    src/gl/pipeline/passes/SpotShadowPass.cpp
    src/gl/pipeline/passes/SkyboxPass.cpp
    src/gl/pipeline/passes/TransparentPass.cpp
    src/gl/pipeline/passes/WboitPass.cpp
    src/gl/pipeline/ForwardRenderPath.cpp
    src/gl/pipeline/Renderer.cpp
    src/gl/pipeline/RenderState.cpp
    src/gl/pipeline/RenderTarget.cpp
)
